UNITSPST (1,step1,INFANTSP,INFANTTEAM,INFANTATTACK,INFANTSPCH)
UNITSPST (step1+1,step2,LIGHTVEHSP,LIGHTVEHTEAM,LIGHTVEHATTACK,LIGHTVEHSPCH)
UNITSPST (step2+1,step3,HEAVYVEHSP,HEAVYVEHTEAM,HEAVYVEHATTACK,HEAVYVEHSPCH)

if g_DisableSeaArmy == 0 then
    UNITSPSHIP (step35+1,step4,AIRSP,SHIPTEAM,SHIPTEAMATTACK,AIRSPCH)
end

UNITSPAIRST (step4+1,step5,INFANTSP,AIRTEAM,AIRATTACK,INFANTSPCH)

SpawnGigaFortressAir()
