JapanAntiInfantryVehicleMICROCONTROL ()
JapanMissileMechaAdvancedMICROCONTROL ()
JapanAntiAirVehicleTech1MICROCONTROL ()
JapanFortressShipMICROCONTROL ()
JapanAntiAirShipMICROCONTROL ()
SovietScoutVehicleMICROCONTROL ()
BIGSHIPCONTROL ()